<!-- Row Highlight Javascript -->
<script type="text/javascript">
    window.onload = function () {
        var tfrow = document.getElementById('tfhover').rows.length;
        var tbRow = [];
        for (var i = 1; i < tfrow; i++) {
            tbRow[i] = document.getElementById('tfhover').rows[i];
            tbRow[i].onmouseover = function () {
                this.style.backgroundColor = '#ffffff';
            };
            tbRow[i].onmouseout = function () {
                this.style.backgroundColor = '#d4e3e5';
            };
        }
    };
</script>

<style type="text/css">
    table.tftable {
        font-size: 12px;
        color: #333333;
        width: 100%;
        border-width: 1px;
        border-color: #729ea5;
        border-collapse: collapse;
    }

    table.tftable th {
        font-size: 12px;
        background-color: #acc8cc;
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #729ea5;
        text-align: left;
    }

    table.tftable tr {
        background-color: #d4e3e5;
    }

    table.tftable td {
        font-size: 12px;
        border-width: 1px;
        padding: 8px;
        border-style: solid;
        border-color: #729ea5;
    }
</style>

<form action="add">
    <input value="Add" type="submit">
</form>

<input value="Show number of last" type="submit" onclick="
    s=prompt('Enter number of last to show','');
    if (s != null) {
        window.location.replace('?last_n='+s);
    }


    ">

<table id="tfhover" class="tftable" border="1">
    <tr>
    <th>HMACKey_id</th>
    <th>method</th>
    <th>uri</th>
    <th>uri_parameters</th>
    <th>date</th>
    <th></th>

    <?php



    foreach ($data as $key => $row) {
        echo "<tr>";

        echo "<td>";
        echo $row->getHmackeyId();
        echo "</td>";

        echo "<td>";
        echo $row->getMethod();
        echo "</td>";

        echo "<td>";
        echo $row->getUri();
        echo "</td>";

        echo "<td>";
        echo $row->getUriParameters();
        echo "</td>";

        echo "<td>";
        echo $row->getDate()->format('d/m/Y');
        echo "</td>";

        ?>
        <td>
            <form action="edit" method="GET">
                <input type="hidden" name="id" value="<?= $row->getId() ?>"/>
                <input type="submit" value="Edit"/>
            </form>

            <form action="remove" method="GET">
                <input type="hidden" name="id" value="<?= $row->getId() ?>"/>
                <input type="submit" value="Remove"/>
            </form>
        </td>
        <?php

        echo "</tr>";
    }



    ?>


</table>

